version: '3.7'
services:
  web:
    container_name: dm_r
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test_task
      - POSTGRES_PASSWORD=test_task
      - POSTGRES_DB=test_task

volumes:
  postgres_data: